name: InfectedManhunt
version: '${project.version}'
main: com.ronlab.infectedmanhunt.InfectedManhuntPlugin
api-version: '26.2'
description: Infected Manhunt mode companion plugin for Ronlab Game Assistant.
authors:
  - ronlab
dependencies:
  server:
    RonlabGameAssistant:
      required: true
      join-classpath: true
      load: BEFORE
